name: better_organizer
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cloud_firestore: ^3.1.8
  contacts_repository:
    path: packages/contacts_repository
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  marquee: ^2.2.1
  provider: ^6.0.2

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
