// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAKotLc7P9Q5MJpEmRQO0Ke4nKQErQhlQ',
    appId: '1:326003106588:web:954e28965b34a7312fd0d9',
    messagingSenderId: '326003106588',
    projectId: 'better-organizer',
    authDomain: 'better-organizer.firebaseapp.com',
    storageBucket: 'better-organizer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCikR7ZokYxyIiYyp0ID8Exft5nDs56Cn0',
    appId: '1:326003106588:android:c2c7da94ab2ce33c2fd0d9',
    messagingSenderId: '326003106588',
    projectId: 'better-organizer',
    storageBucket: 'better-organizer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4T1sylOmn8kArkrLXvxfNIk-Z8vrBcE',
    appId: '1:326003106588:ios:3de8a6419ed605692fd0d9',
    messagingSenderId: '326003106588',
    projectId: 'better-organizer',
    storageBucket: 'better-organizer.appspot.com',
    iosClientId: '326003106588-grsv6kmb95a5gaqquspi7m67vpo7nt6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4T1sylOmn8kArkrLXvxfNIk-Z8vrBcE',
    appId: '1:326003106588:ios:3de8a6419ed605692fd0d9',
    messagingSenderId: '326003106588',
    projectId: 'better-organizer',
    storageBucket: 'better-organizer.appspot.com',
    iosClientId: '326003106588-grsv6kmb95a5gaqquspi7m67vpo7nt6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterOrganizer',
  );
}
